# Generated by Django 3.1.2 on 2020-10-24 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0002_auto_20201024_1451")]

    operations = [
        migrations.RemoveField(model_name="book", name="published_date"),
        migrations.AddField(
            model_name="book",
            name="purchased_at",
            field=models.DateField(default=datetime.date(2020, 10, 24)),
        ),
    ]
