# Generated by Django 3.1.2 on 2020-10-24 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0003_auto_20201024_1456")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="purchased_at",
            field=models.DateField(
                default=datetime.datetime(2020, 10, 24, 14, 56, 41, 583268)
            ),
        )
    ]
