# Generated by Django 3.1.2 on 2020-10-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0004_auto_20201024_1456")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="book", name="description", field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name="book", name="purchased_at", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="book",
            name="sub_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
