# Generated by Django 3.1.2 on 2020-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0005_auto_20201024_1513")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=5
            ),
        )
    ]
