# Generated by Django 3.1.2 on 2020-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0006_book_sale_price")]

    operations = [
        migrations.AddField(
            model_name="book", name="published_at", field=models.DateField(null=True)
        ),
        migrations.AddField(
            model_name="book",
            name="type",
            field=models.CharField(
                choices=[
                    ("NEW_BOOKS", "New Purchased Books"),
                    ("USED_BOOKS", "Used Purchased Books"),
                    ("E_BOOKS", "E-Books"),
                ],
                default="NEW_BOOKS",
                max_length=30,
            ),
        ),
    ]
